---
- hosts: localhost
  tasks:
    - name: Create default containers
      docker_container:
        name: nexus
        image: sonatype/nexus3
        ports:
          - 8081:8081
        volumes:
          - /etc/nexus-data:/nexus-data
